replicaCount: 1

webapp:
  name: flask-demo
  group: flask-demo
  path: /
  welcomeMessage: "Welcome to the Flask Demo! gdicker1 lightly edited it"
  container: 
    image: docker.io/ncging/argo-flask-demo:dne-bad-tag
    port: 5000